
development:
  adapter: postgresql
  encoding: unicode
  database: voter_development
  host: localhost
  pool: 5
  username: saikg
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: voter_test
  host: localhost
  pool: 5
  username: saikg
  password: postgres

production:
  adapter: postgresql