# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb240653089b5e592bceb97843395894b340af594b3926b6784b396d820aa478f9e4ab3218344db6b0cf7cf27569eb3dbf58c72c9ba095fa87814e27d198fa8

test:
  secret_key_base: 3379b914765761621d845801e6891d26ad25edc8617d8c0a8865b22dc560aea4f700d1e55647b422c6cd53e4d6c618a82be75acf94eee9da34680ff3b9283fef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
